apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecotrack-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - api-staging.ecotrack.earth
    - staging.ecotrack.earth
    - mlflow-staging.ecotrack.earth
    secretName: ecotrack-staging-tls
  rules:
  - host: api-staging.ecotrack.earth
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-python
            port:
              number: 80
  - host: staging.ecotrack.earth
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 80
  - host: mlflow-staging.ecotrack.earth
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mlflow
            port:
              number: 80