apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - api-python/
  - web/
  - worker/
  - postgres/
  - redis/
  - minio/
  - neo4j/
  - mlflow/
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: ecotrack
  app.kubernetes.io/managed-by: kustomize