apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-python
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: api-python
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        env:
        - name: ENVIRONMENT
          value: "production"
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: api-python