apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-python-pdb
  namespace: ecotrack
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: api-python
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-pdb
  namespace: ecotrack
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: worker-pdb
  namespace: ecotrack
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: worker